name: Upstream Sync

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v5

      - name: Sync Upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.2
        with:
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_repo: deepseek-ai/deepseek-harness
          upstream_sync_branch: master
          target_sync_branch: master
